/**
 * Application Constants
 */

// Error codes
export const ERROR_CODES = {
  // Authentication
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // Not Found
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  
  // Conflicts
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_BARCODE: 'DUPLICATE_BARCODE',
  DUPLICATE_STUDENT_ID: 'DUPLICATE_STUDENT_ID',
  
  // Book Operations
  BOOK_NOT_AVAILABLE: 'BOOK_NOT_AVAILABLE',
  BORROWING_LIMIT_EXCEEDED: 'BORROWING_LIMIT_EXCEEDED',
  OVERDUE_BOOKS: 'OVERDUE_BOOKS',
  UNPAID_FINES: 'UNPAID_FINES',
  
  // Server Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  
  // Registration
  INVALID_ACTIVATION_CODE: 'INVALID_ACTIVATION_CODE',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  STUDENT_NOT_PRE_REGISTERED: 'STUDENT_NOT_PRE_REGISTERED'
} as const

// Default system settings
export const DEFAULT_SETTINGS = {
  DEFAULT_LOAN_PERIOD_DAYS: 14,
  MAX_RENEWALS: 2,
  FINE_PER_DAY: 5.0,
  MAX_BORROWING_LIMIT_STUDENT: 3,
  RESERVATION_EXPIRY_HOURS: 24
} as const

// Pagination defaults
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100
} as const

// User roles
export const USER_ROLES = {
  STAFF: 'STAFF',
  STUDENT: 'STUDENT'
} as const

// User status
export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

// Book status
export const BOOK_STATUS = {
  AVAILABLE: 'AVAILABLE',
  BORROWED: 'BORROWED',
  RESERVED: 'RESERVED',
  MAINTENANCE: 'MAINTENANCE',
  LOST: 'LOST',
  DAMAGED: 'DAMAGED'
} as const

// Transaction status
export const TRANSACTION_STATUS = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED',
  OVERDUE: 'OVERDUE'
} as const
